export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    LOGIN:"LOGIN",
    SIGNUP:"SIGNUP",
    LOGOUT:"LOGOUT",
    SET_CUSTOMER_DETAIL:"SET_CUSTOMER_DETAIL",
    SHOW_CART:"SHOW_CART",
    ADD_TO_CART:"ADD_TO_CART",
    SET_CART:"SET_CART",
    SHOW_ORDERS:"SHOW_ORDERS",
    ADD_CATEGORY:"ADD_CATEOGRY",
    SET_CATEGORY:"SET_CATEGORY",
    DELETE_CATEGORY:"DELETE_CATEGORY",
    ADD_ADDRESS:"ADD_ADDRESS"
  };